#------------------------------------------------------------------------------
# Portions of this file are Copyright (C)2018 Robert Cowart
# 
# Portions of this file are subject to the Robert Cowart Public License (the
# "License") and may not be used or distributed except in compliance with the
# License. You may obtain a copy of the License at:
# 
# http://www.koiossian.com/public/robert_cowart_public_license.txt
# 
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
# the specific language governing rights and limitations under the License.
# 
# The Original Source Code was developed by Robert Cowart. Portions created by
# Robert Cowart are Copyright (C)2018 Robert Cowart. All Rights Reserved.
#------------------------------------------------------------------------------

version: '3'

services:
  elastiflow-elasticsearch-oss:
    image: robcowart/elastiflow-elasticsearch-oss:3.3.0_6.4.1
    container_name: elastiflow-elasticsearch-oss
    restart: 'always'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      # JVM Heap size
      #   - this should be at least 2GB for simple testing, receiving only a few flows per second.
      #   - for production environments upto 31GB is recommended.
      ES_JAVA_OPTS: '-Xms4g -Xmx4g'
    ports:
      - 9200:9200/tcp
    networks:
      - stack
    
    volumes:
      - elk_stack_volume:/usr/share/elasticsearch/data

  elastiflow-kibana-oss:
    image: robcowart/elastiflow-kibana-oss:3.3.0_6.4.1
    container_name: elastiflow-kibana-oss
    restart: 'always'
    depends_on:
      - elastiflow-elasticsearch-oss
    ports:
      - 5601:5601/tcp
    networks:
      - stack

  elastiflow-logstash-oss:
    image: robcowart/elastiflow-logstash-oss:3.3.0_6.4.1
    container_name: elastiflow-logstash-oss
    restart: 'always'
    depends_on:
      - elastiflow-elasticsearch-oss
    environment:
      # JVM Heap size - this MUST be at least 4GB (6GB preferred)
      LS_JAVA_OPTS: '-Xms4g -Xmx4g'

      # ElastiFlow global configuration
      ELASTIFLOW_GEOIP_CACHE_SIZE: 8192
      ELASTIFLOW_GEOIP_LOOKUP: "true"
      ELASTIFLOW_ASN_LOOKUP: "true"
      ELASTIFLOW_KEEP_ORIG_DATA: "true"
      ELASTIFLOW_DEFAULT_APPID_SRCTYPE: "__UNKNOWN"

      # Name resolution option
      ELASTIFLOW_RESOLVE_IP2HOST: "false"
      ELASTIFLOW_NAMESERVER: "127.0.0.1"
      ELASTIFLOW_DNS_HIT_CACHE_SIZE: 25000
      ELASTIFLOW_DNS_HIT_CACHE_TTL: 900
      ELASTIFLOW_DNS_FAILED_CACHE_SIZE: 75000
      ELASTIFLOW_DNS_FAILED_CACHE_TTL: 3600

      # Netflow - UDP input options
      ELASTIFLOW_NETFLOW_UDP_WORKERS: 4
      ELASTIFLOW_NETFLOW_UDP_QUEUE_SIZE: 4096
      ELASTIFLOW_NETFLOW_UDP_RCV_BUFF: 33554432
      # Netflow - Timestamp options
      ELASTIFLOW_NETFLOW_LASTSW_TIMESTAMP: "false"
      ELASTIFLOW_NETFLOW_TZ: "UTC"

      # sFlow - UDP input options
      ELASTIFLOW_SFLOW_UDP_WORKERS: 4
      ELASTIFLOW_SFLOW_UDP_QUEUE_SIZE: 4096
      ELASTIFLOW_SFLOW_UDP_RCV_BUFF: 33554432

      # IPFIX - UDP input options
      ELASTIFLOW_IPFIX_UDP_WORKERS: 4
      ELASTIFLOW_IPFIX_UDP_QUEUE_SIZE: 4096
      ELASTIFLOW_IPFIX_UDP_RCV_BUFF: 33554432

    ports:
      - 2055:2055/udp
      - 4739:4739/tcp
      - 4739:4739/udp
      - 6343:6343/udp
    
    networks:
      - stack

networks: {
  stack: {}
}

volumes:
  elk_stack_volume:
